#!/bin/bash

set -eux

function get_brew() {
  brew="$(yaml read ./manifest.yml homebrew[$1].brew)"
}

function get_cask() {
  cask="$(yaml read ./manifest.yml homebrew[$1].cask)"
}

brew update

get_brew 0
get_cask 0
brew install "${cask}/tap/${brew}"
brew upgrade "${brew}"

