#!/bin/bash

set -ux

function get_total_brews() {
  length="$(yaml read ./manifest.yml homebrew.*.brew | wc -l | tr -d '[:space:]')"
  total_brews="$(expr $length - 1)"
}

function get_brew() {
  brew="$(yaml read ./manifest.yml homebrew[$1].brew)"
}

function get_cask() {
  cask="$(yaml read ./manifest.yml homebrew[$1].cask)"
}

get_total_brews

for i in $(eval echo "{0..$total_brews}")
do
  get_brew $i
  get_cask $i
  brew install "${cask}/tap/${brew}"
  brew upgrade "${brew}"
done

